"""Add button_url attribute to the Notification table

Revision ID: 4e915032426b
Revises: f557918c9f6b
Create Date: 2025-03-28 12:48:42.578530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e915032426b"
down_revision: Union[str, None] = "f557918c9f6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification", sa.Column("button_url", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "button_url")
    # ### end Alembic commands ###
