"""Add intermediate table

Revision ID: 38cf8e408509
Revises: 4e915032426b
Create Date: 2025-04-11 13:13:31.884391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38cf8e408509"
down_revision: Union[str, None] = "4e915032426b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_document",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_notification_document_document_id_document"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notification.id"],
            name=op.f("fk_notification_document_notification_id_notification"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "notification_id",
            "document_id",
            name=op.f("pk_notification_document"),
        ),
    )
    op.create_index(
        op.f("ix_document_buffer"), "document", ["buffer"], unique=False
    )
    op.drop_constraint(
        "fk_document_notification_id_notification",
        "document",
        type_="foreignkey",
    )
    op.drop_column("document", "notification_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column(
            "notification_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "fk_document_notification_id_notification",
        "document",
        "notification",
        ["notification_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_document_buffer"), table_name="document")
    op.drop_table("notification_document")
    # ### end Alembic commands ###
